site_name: SootUp
site_url: https://soot-oss.github.io/SootUp/
repo_url: https://github.com/soot-oss/SootUp/
edit_uri: edit/develop/docs/

nav:
    - Home: index.md
    - Installation: installation.md
    - General information:
      - Design Decisions: whatsnew.md
      - Getting started: getting-started.md
      - Jimple: jimple.md
      - Call Graph Construction: call-graph-construction.md
      - Advanced Topics: advanced-topics.md
  #   - Writing Analyses: analyses.md
    - More information:
      - Javadoc: /SootUp/apidocs
      - FAQ: faq.md
      - Used by: tools.md

theme:
  palette:
    primary: white
  name: material
  logo: ./SootUpLogo.svg
  favicon: ./icon.svg
  features:
    - navigation.sections

plugins:
  - tooltips
  - search
  - include:
      src_path: 'sootup.examples/src/test/java/sootup/examples'

extra_css:
  - css/hint.min.css

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
      extend_pygments_lang:
        - name: jimple
          lang: lspserver
          options:
            filetype: jimple
            # the path of the jimplelsp.jar needs to be the same as in the gh-pages.yml workflow
            lspcommand: "java -jar ./jimplelsp.jar"

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.tabbed:
      alternate_style: true

extra:
  version:
    provider: mike