name: Documentation 
on:
  push:
    branches: 
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # download the latest jimplelsp and (re)name/move the jar to ~/jimplelsp.jar which is
      - uses: robinraju/release-downloader@v1.3
        with:
            repository: "swissiety/JimpleLSP"
            latest: true
            fileName: "*.jar"
            out-file-path: "jimplelspdir"
      - run: mv jimplelspdir/*.jar ~/jimplelsp.jar
      # install mk_docs plugins
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-tooltips
      - run: pip install git+https://github.com/RedisLabs/mkdocs-include.git
      - run: pip install git+https://github.com/swissiety/LspLexer4Pygments.git
      # deploy gh-pages
      - run: mkdocs gh-deploy --force
