name: Delete obsolete Documentation
on:
  pull_request:
    types:
      - closed
    paths:
      - 'mkdocs.yml'
      - 'sootup.examples/**'
      - 'docs/**'

permissions:
  contents: write

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mike
      - run: pip install --upgrade setuptools
      - run: git fetch origin gh-pages --depth=1
      - name: Configure git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - run: mike delete ${{ github.head_ref }} --push