# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - '**/badges/jacoco.svg'  # don't loop infinitely  ;-)

  pull_request:
    branches: [ develop ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:

  JDK8:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build (JDK8)
        run: mvn clean compile -B -Dfmt.skip -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Test (JDK8)
        run: mvn -pl '!de.upb.swt.soot.tests' -am verify -B -Dfmt.skip -PJava8 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: coverage-exec-jdk8
          path: |
                  */target/coverage-reports/jacoco-ut-jdk8.exec
                  !de.upb.swt.soot.tests/

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-reports-jdk8
          path: |
                  */target/surefire-reports
                  !de.upb.swt.soot.tests/


  JDK9:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.9
        uses: actions/setup-java@v1
        with:
          java-version: 1.9
      - name: Check Format
        run: mvn com.coveo:fmt-maven-plugin:check -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Build (JDK9)
        run: mvn clean compile -B -Dfmt.skip -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Test (JDK9)
        run: mvn -pl '!de.upb.swt.soot.tests' -am verify -B -Dfmt.skip -PJava9 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: coverage-exec-jdk9
          path: |
            */target/coverage-reports/jacoco-ut-jdk9.exec
            !de.upb.swt.soot.tests/

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-reports-jdk9
          path: |
            */target/surefire-reports
            !de.upb.swt.soot.tests/
    
    
    

    # takes a long time to run - so just run them when PR is not draft anymore
  IntegrationTest:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build (IntegrationTest)
        run: mvn clean compile -B -Dfmt.skip -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Test (IntegrationTest)
        run: mvn -pl de.upb.swt.soot.tests -am verify -B -Dfmt.skip -PIntegrationTest -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - run: tree

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: coverage-exec-integrationtest
          path: |
            */target/coverage-reports/jacoco-ut-integrationtest.exec

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-reports-integrationtest
          path: |
            */target/surefire-reports



  CoverageReport:
    runs-on: ubuntu-latest
    needs: [ JDK9, JDK8, IntegrationTest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # needed to match coverage with its "classid"s.. FIXME: classids  can(and do sometimes) not match i.e. are currently ignored/skipped in the report for jdk9 coverage!
      - run: mvn clean compile -B -Dfmt.skip -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: Download uploaded artifacts jdk8
        uses: actions/download-artifact@v3
        with:
          name: coverage-exec-jdk8

      - name: Download uploaded artifacts jdk9
        uses: actions/download-artifact@v3
        with:
          name: coverage-exec-jdk9
      - name: Download uploaded artifacts integrationtest
        uses: actions/download-artifact@v3
        with:
           name: coverage-exec-integrationtest

      - name: merge coverage reports
        run:  mvn -ntp jacoco:merge@merge-results

      - name: aggregtate coverage reports across java versions
        run: mvn -ntp jacoco:report-aggregate@generate-coverage-report

      - name: upload aggregated coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: aggregated-coverage-report
          path: ${{ github.workspace }}/report/target/jacoco-aggregate/

      - name: jacoco-badge-generator
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.6.1
        with:
          jacoco-csv-file: report/target/jacoco-aggregate/jacoco.csv

      - name: Comment Coverage info
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: coverage-pr-message
          recreate: true
          message: |
            ***Test Coverage***
            Total coverage ${{ steps.jacoco.outputs.coverage }}
            Changed Files coverage ${{ steps.jacoco.outputs.branches }}

      - name: Commit the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'commit badge'
          add: '**/badges/jacoco.svg'
