# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs: 
  JDK8:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check Format
      run: mvn com.coveo:fmt-maven-plugin:check
    - name: Build (JDK8)
      run: mvn clean compile -Dfmt.skip
    - name: Test (JDK8)
      run: mvn verify -Dfmt.skip -PJava8
    - name: Coverage     
      env: 
        SUBMODULES: java.core, java.bytecode, java.sourcecode, java.callgraph
      run: |
           sudo mkdir target/coverage-reports
           for item in $SUBMODULES
           do 
             sudo mv de.upb.swt.soot.${item}/target/coverage-reports/jacoco-ut.exec target/coverage-reports/jacoco-ut-${item}-jdk8.exec
             sudo rm -f de.upb.swt.soot.${item}/target/coverage-reports/aggregate.exec
           done
           mvn validate
           ls -R .
     
  JDK9:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.9
      uses: actions/setup-java@v1
      with:
        java-version: 1.9
    - name: Build (JDK9)
      run: mvn clean compile -Dfmt.skip
    - name: Test (JDK9)
      run: mvn verify -Dfmt.skip -PJava8
   
 
      
