# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:

  JDK8:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build (JDK8)
        run: mvn clean compile -B -Dfmt.skip -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Test (JDK8)
        run: mvn -pl '!de.upb.swt.soot.tests' -am verify -B -Dfmt.skip -PJava8 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: coverage-reports-jdk8
          path: |
                  */target/coverage-reports
                  !*/target/coverage-reports/jacoco-ut-jdk8.exec
                  !de.upb.swt.soot.tests/

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: coverage-exec-jdk8
          path: |
                  */target/coverage-reports/jacoco-ut-jdk8.exec
                  !de.upb.swt.soot.tests/

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-reports-jdk8
          path: |
                  */target/surefire-reports
                  !de.upb.swt.soot.tests/


  JDK9:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.9
        uses: actions/setup-java@v1
        with:
          java-version: 1.9
      - name: Check Format
        run: mvn com.coveo:fmt-maven-plugin:check -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Build (JDK9)
        run: mvn clean compile -B -Dfmt.skip -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Test (JDK9)
        run: mvn -pl '!de.upb.swt.soot.tests' -am verify -B -Dfmt.skip -PJava9 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - run: tree
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: coverage-reports-jdk9
          path: |
            */target/coverage-reports
            !*/target/coverage-reports/jacoco-ut-jdk9.exec
            !de.upb.swt.soot.tests/

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: coverage-exec-jdk9
          path: |
            */target/coverage-reports/jacoco-ut-jdk9.exec
            !de.upb.swt.soot.tests/

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-reports-jdk9
          path: |
            */target/surefire-reports
            !de.upb.swt.soot.tests/
    
    
    

    # takes a long time to run - so just run them when PR is not draft anymore
  IntegrationTest:
    if: ${{ !github.event.pull_request.draft && false }}      #TODO: remove false!

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build (IntegrationTest)
        run: mvn clean compile -B -Dfmt.skip -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Test (IntegrationTest)
        run: mvn -pl de.upb.swt.soot.tests -am verify -B -Dfmt.skip -PIntegrationTest -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: coverage-reports-integrationtest
          path: |
            */target/coverage-reports
            !*/target/coverage-reports/jacoco-ut-integrationtest.exec
            !de.upb.swt.soot.tests/

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: coverage-exec-integrationtest
          path: |
            */target/coverage-reports/jacoco-ut-integrationtest.exec
            !de.upb.swt.soot.tests/

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-reports-integrationtest
          path: |
            */target/surefire-reports
            !de.upb.swt.soot.tests/

  CoverageReport:
    runs-on: ubuntu-latest
    #TODO: need and merge IntegrationTest
    needs: [ JDK9, JDK8 ] #, IntegrationTest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Download uploaded artifacts jdk8
        uses: actions/download-artifact@v3
        with:
          name: coverage-exec-jdk8

      - name: Download uploaded artifacts jdk9
        uses: actions/download-artifact@v3
        with:
          name: coverage-exec-jdk9
#      - name: Download uploaded artifacts integrationtest
#        uses: actions/download-artifact@v3
#        with:
#           name: coverage-reports-integrationtest

      #debug

      - run: tree ${{ github.workspace }}


      # merge reports from java8,java9
 #     - run:  mvn jacoco:merge@merge-results -B
 #     - run: test -f ${{ github.workspace }}/target/coverage-reports/aggregate.exec || echo "::error file=aggregate.exec,::Merged coverage file was not created."

      # aggregtate reports
      - run: mvn jacoco:report@generate-coverage-report -B

      #debug
      - run: tree ${{ github.workspace }}

      - uses: actions/upload-artifact@v3
        with:
          name: aggregated-coverage-report
          path: ${{ github.workspace }}/report/target/site/jacoco-aggregate/

      - name: Add coverage comment to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/report/target/site/jacoco-aggregate/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: Code Coverage
          debug-mode: false

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"