name: Download Random JARs from Maven

on:
  push:
    branches: [ develop ]
jobs:
  download-jars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run:
          pip install requests

      - name: Download random JARs
        run: |
          python .github/download_jars.py

      - name: Upload JARs
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: downloaded_jars/

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify Maven
        run: mvn -v

      - name: Run tests on downloaded JARs
        run: |
          for jar in downloaded_jars/*.jar; do
            echo "Testing $jar"
            mvn -Dtest=sootup.java.bytecode.inputlocation.RandomJarTest test -DjarPath="$jar" || true
          done